/**
 * sync-config.js
 *
 * Generates functions/.env from src/config/.firebase.js.
 * Run this before starting the emulator so it always uses the
 * same project and database URL as the frontend config.
 *
 * Usage:  node scripts/sync-config.js
 * Or via npm:  npm run sync-config
 */

const fs   = require("fs");
const path = require("path");
const { readFirebaseConfig } = require("./read-firebase-config");

const { projectId, databaseURL } = readFirebaseConfig();

const envContent = `# Auto-generated by scripts/sync-config.js — do not edit manually.
# Change src/config/.firebase.js and re-run to update.
DATABASE_URL=${databaseURL}
`;

const envPath = path.resolve(__dirname, "../.env");
fs.writeFileSync(envPath, envContent);

console.log("Synced Firebase config → functions/.env");
console.log(`  projectId:   ${projectId}`);
console.log(`  databaseURL: ${databaseURL}`);
