name: Auto-Assign New Issues

on:
  issues:
    types: [opened]

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Required to assign issues
    steps:
      - name: Assign issue to creatoratnight
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['creatoratnight']
            })
